### ISSUE TITLE
Autocorrect Pop-Up Missing When Predictive is Disabled

### ISSUE THREAD

**Issue by Hydroxing** [MTACS/DopeConvos#100]
**Describe the bug**
MTACS, I'd like to first apologize about the people who use your tweak that can't follow simple directions by reading. Anyhow, when Predictive is Disabled in Settings, the pop-up for autocorrect no longer appears making it nearly impossible to purposefully type a typo. Say, trying to type "doesnt" instead of doesn't won't work because autocorrect immediately corrects it without the optional pop-up.

**To Reproduce**

1. Go to Settings>General>Keyboard>Predictive [OFF]
2. Force Quit Messages.app process if running
3. Open Messages.app
4. Find a conversation to type in
5. Enter any phrase or characters that would typically force an autocorrection ("y'all" [without quotes] usually works.)
6. _Notice there is no autocorrection pop-up to correct or ignore correction_
7. Tapping space bar to type next word autocorrects word whether you wanted it to correct or not.

**Expected behavior**
The expected behavior is that the small autocorrect suggestion bubble appears when mistyping or typing a shortcut word in the messages.app.

**Screenshots**
https://streamable.com/zjbzik there is a link to watch a 53 second video describing and showing the bug in action.

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [13.5]
 - Package Manager: [Zebra, & Cydia]
 - Tweak Version: [2.9]

**Additional context**
I sincerely apologize for the illiterates that can't read the instructions on how to describe a bug. It's simple and reading is not hard. I'm also a QA engineer at a fintech company so maybe I'm meticulous about my bug reports.

**Comment by nahtedetihw** [comment]
there was a crash in autocorrect, to get around that we had to remove the popup. autocorrect still works though when you press space
