### ISSUE TITLE
Changing background image

### ISSUE THREAD

**Issue by joek1ng4312** [MTACS/DopeConvos#102]
**Describe the bug**

While enabling a preset to customize, The background image doesn’t update when changed for conversation/chat backgrounds after pressing apply or apply/respring
**To Reproduce**
Self explanatory

**Expected behavior**
The background image to update to what I change it to.
**Screenshots**

**Desktop (please complete the following information):**
- Device type: iPhone X
 - iOS Version: 13.3.5
 - Package Manager: Sileo
 - Tweak Version: 3.0

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
