### ISSUE TITLE
Dope Convos

### ISSUE THREAD

**Issue by pthomp456** [MTACS/DopeConvos#103]
![157159BC-12D2-4D97-BC0D-FDC916FDF8FA](https://user-images.githubusercontent.com/67829270/86512822-fafab800-bdca-11ea-8b0a-cb9b78ba756b.png)

So I go into the background settings to apply a wallpaper, but there is no setting for it. There is only the configuration for blurs, so I thought maybe you couldn't do it, then I read the explanation and it said there was an option to upload a picture. It would beuch appreciated if this could be fixed. I just saw a post about the 3.0 update on Reddit and the tweak looked sweet, but it's a little confusing to use since you can't see what you're doing until you apply the changes. The presets are still pretty nice, but it would be sweet if there was an adaptive preset like in the Reddit post. Thanks for the help

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
