### ISSUE TITLE
Bug found within messages 

### ISSUE THREAD

**Issue by gnocha** [MTACS/DopeConvos#108]
When attempting to view info for a contact in messages it will not let you. If the contact is pinned when the info button is tapped, nothing happens. Only if the contact is pinned can you view the info screen 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
I have no idea what info button you're referring to. Tried looking for it and have no clue where that is
