### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by pitbullmom89** [MTACS/DopeConvos#110]
**Describe the bug**
After updating my messages app doesn’t open. It will show a white screen for about 15-20 seconds and then close. 
**To Reproduce**

**Expected behavior**
I expected me to see my messages app open
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X] iPhone XS Max 
 - iOS Version: [ex. 13.3.1] 13.5
 - Package Manager: [ex. Zebra, Installer, Cydia] cydia
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**
I also noticed that I can no longer add my own image as a background

**Comment by nahtedetihw** [comment]
resolved in 4.0
