### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by XOOLHP** [MTACS/DopeConvos#111]
**Describe the bug**
Tweak not working and crash my device

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [3.2]

**Additional context**
When a open Messages App, fix screen white an crash app

**Comment by nahtedetihw** [comment]
if you have Rainbow tweak, it will cause crash. Remove tweak or use Choicy to only allow DopeConvos in Messages app
