### ISSUE TITLE
Old style before 3.0 crash app and goes to safe mode 

### ISSUE THREAD

**Issue by Mighel881** [MTACS/DopeConvos#113]
[Lunar ](https://pastebin.com/CaYTBY8W) **Describe the bug**

**To Reproduce**
Import on settings go out and reopen message App 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [ex. 13.5]
 - Package Manager: [ex. Zebra, Cydia]
 - Tweak Version: [3.0]

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
