### ISSUE TITLE
All Editable Sections Are Missing Settings

### ISSUE THREAD

**Issue by Hydroxing** [MTACS/DopeConvos#114]
**Describe the bug**
After updating to 3.3, the sections for each customizable setting (i.e. Conversations, Bubbles, Tint, etc.) are missing.

**To Reproduce**
1) Install DopeConvos 3.3
2) Respring after installing
3) Go to Preference Pane in Settings for DopeConvos
4) Attempt to view any settings pane that can be changed in the Messages app
5) Nothing loads

**Expected behavior**
All settings appear and can be edited.

**Screenshots**
![25CA8D67-2F14-4DCD-BC4F-3CB49D622831](https://user-images.githubusercontent.com/47262814/86546068-d43e9d80-bf00-11ea-99f4-53325c523b42.png)
![7A4D2D5C-BE83-4881-BB5C-D5D6D4E343E9](https://user-images.githubusercontent.com/47262814/86546070-d4d73400-bf00-11ea-8f1b-d74307308095.png)

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [13.5]
 - Package Manager: [Zebra, Cydia]
 - Tweak Version: [3.3]

**Additional context**
This happened after I attempted to import a blank preset. How? Tapping “Import” under Old Presets then tapping “Okay” when no data was entered in the paste box.

**Comment by BetaMoose** [comment]
Hey @Hydroxing,
    I got mine to work again just by changing the main theme to dark and then back again. Not saying this isn’t a bug, just trying to get ya back to using it how it’s supposed to again.

**Comment by nahtedetihw** [comment]
resolved in 4.0
