### ISSUE TITLE
Dopeconvos 3.3 - 3.4

### ISSUE THREAD

**Issue by Booz8819** [MTACS/DopeConvos#115]
**Describe the feature you'd like to be added**
I love all the work you guys do and love this tweak. My favorite so far has been 2.9 after that it’s been difficult with a lot of the setting not being there like 2.9. I get the improvements and the changes but just want it to where it was super simple and easy. I keep upgrading and get exited for each update by I catch myself downgrading to 2.9 again. Thanks for all the hard work

**Comment by nahtedetihw** [comment]
resolved in 4.0
