### ISSUE TITLE
tweak makes messages not open

### ISSUE THREAD

**Issue by trashfire-tothemax** [MTACS/DopeConvos#116]
**Describe the bug**
upon enabling tweak, messages will not load. it immediately closes out. 

**To Reproduce**
enable tweak, try to open messages. doesn’t seem to matter what i change in the tweak - changing nothing and enabling still results in messages quitting life. 

**Expected behavior**
i expect messages to work with any changes made from the tweak 

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone 11 pro max]
 - iOS Version: [13.3.1]
 - Package Manager: [Cydia]
 - Tweak Version: [3.1]

**Additional context**
other tweaks i’m using: springtomize 5, lynx, midevice, cylinder, axon

**Comment by nahtedetihw** [comment]
remove Rainbow tweak or use Choicy to only allow DopeConvos in Messages App
