### ISSUE TITLE
Bring back the “remove bubble tail” option 

### ISSUE THREAD

**Issue by jooseemanuel** [MTACS/DopeConvos#119]
Could you please bring back the “remove bubble tail” option, it was in the version 2.9 but not in the newest one

**Comment by sac396** [comment]
It's there for me. Settings > DopeConvos > Bubbles > Remove Bubble Tails

**Comment by jooseemanuel** [comment]
It’s not for me

**Comment by nahtedetihw** [comment]
resolved in 4.0
