### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pthomp456** [MTACS/DopeConvos#120]
Hello, after your most recent update, no features of the tweak are working. I appreciate all the hard work you put in the tweak and the updates you've put in to make certain features work again, just thought I would bring this to your attention. I've tried restarting the springboard and reinstalling it but nothings working.
![D21A13A2-ABDE-40EC-ADBC-711472B7DDDE](https://user-images.images.githubusercontent.com/67829270/86629219-13203200-bf99-11ea-8f0b-71799e277ef4.png)
![668815D6-86A8-43EC-9DC4-F64CBAEC434F](https://user-images.githubusercontent.com/67829270/86629221-13b8c880-bf99-11ea-802d-d788218c1db0.png)

**Comment by nahtedetihw** [comment]
resolved in 4.0
