### ISSUE TITLE
Game pigeon games dont open

### ISSUE THREAD

**Issue by dilroopg** [MTACS/DopeConvos#121]
**Describe the bug**
game pigeon immessage games wont open
**To Reproduce**
click on the play button
**Expected behavior**
it kinda glitches for a second then doesn't open
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
Please enable Disable Mask On Images in DopeConvos>Main Settings>Bubbles>Disable Mask On Images
