### ISSUE TITLE
Settings isn’t working

### ISSUE THREAD

**Issue by hi-fi-si** [MTACS/DopeConvos#122]
**Describe the bug**
The tweak installs fine but when I go to the settings and I try to edit anything it is a blank page with the title like “backround” or “title 
**To Reproduce**
I’m not sure how to replicate this
**Expected behavior**
To have the ability to edit my messages
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone 11]
 - iOS Version: [ex. 13.2.1] (I think)
 - Package Manager: [ Cydia]
 - Tweak Version: [Newest version]

**Additional context**

**Comment by Qwerty125** [comment]
Same thing happening to me.

**Comment by nahtedetihw** [comment]
resolved in 4.0
