### ISSUE TITLE
No options

### ISSUE THREAD

**Issue by alexsanchezkid** [MTACS/DopeConvos#127]
**Describe the bug**
I have no options to change in any menus once opened. I can only revert back to the old preset i had before the update.

**To Reproduce**
Steps to reproduce the behavior: tried updating all apps required and reinstalling them. Respringing. Menus don’t show up with anything I’ve tried so far.

**Expected behavior**
Just to get the menus back if I wanna customize messages again

**Desktop (please complete the following information):**
- Device type: [iPhone XR
 - iOS Version: 13.5.0
 - Package Manager: CYDIA
 - Tweak Version: Latest Version

**Additional context**
Not the biggest worry in the world cause I like my setup rn. But I wanted to see the new options you know they seem awesome

**Comment by nahtedetihw** [comment]
resolved in 4.0
