### ISSUE TITLE
I cannot make edits in anything. 

### ISSUE THREAD

**Issue by ghoul-pio** [MTACS/DopeConvos#129]
![80E1A679-3AD5-4A04-B992-66553A9A2ED2](https://user-images.githubusercontent.com/68258391/87369574-b216d200-c535-11ea-9c33-34e690ca300f.png)
![F6AC85C9-773B-448F-8D61-BD66BBDC7E4A](https://user-images.githubusercontent.com/68258391/87369579-b4792c00-c535-11ea-9f70-14d07baff472.png)

**Describe the bug
So basically I purchase the app and it was working fine. Then I updated it and it doesn’t let me make changes. I tried reinstalling it and nothing helps.

**To Reproduce**
Steps to reproduce the behavior: So basically I changed my layout added backgrounds and updates the tweak.

**Expected behavior**
A clear and concise description of what you expected to happen. I can’t making any changes.

**Screenshots**
![24E68BB3-093E-42CD-991E-DAE155771F32](https://user-images.githubusercontent.com/68258391/87369637-d672ae80-c535-11ea-9fd9-39717c574415.png)
![BCB93E99-056D-403D-BD4C-51A8CB70D2CB](https://user-images.githubusercontent.com/68258391/87369640-d83c7200-c535-11ea-8ffa-3355c1c37b04.png)

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page] latest version 3.3

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
