### ISSUE TITLE
Add function to change color

### ISSUE THREAD

**Issue by trivjedn00m** [MTACS/DopeConvos#13]
Add a function to change the color of that line and font.
![82A55CA3-9460-41D2-83A7-37132CBD8C68](https://user-images.githubusercontent.com/56149020/79682939-baa58800-8226-11ea-8ebc-049ba351e485.jpeg)
![D204F998-E565-4F91-9185-F9F00EE6E935](https://user-images.githubusercontent.com/56149020/79682942-bda07880-8226-11ea-91a1-29f687dc1982.jpeg)

**Comment by nahtedetihw** [comment]
This has been introduced as of version 1.2
