### ISSUE TITLE
Convo Text color is the same as tint color

### ISSUE THREAD

**Issue by JAKESNAKE523** [MTACS/DopeConvos#131]
**Describe the bug**
When using custom tint color, it also changes the color of the text of the most recent message on the conversations.
**To Reproduce**
Use a custom tint color

**Expected behavior**
Have either normal text color or choose another custom one.

**Screenshots**
![79D8EF4C-1DED-45BF-87E2-C3C26F0AAF58](https://user-images.githubusercontent.com/30319043/87865293-0a384480-c939-11ea-9147-7bf77eedd6c8.jpeg)

**Desktop (please complete the following information):**
- Device type: iPhone XR
 - iOS Version: 13.5
 - Package Manager: Sileo
 - Tweak Version: 3.3

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
