### ISSUE TITLE
Cannot change settings

### ISSUE THREAD

**Issue by SeaJayClark** [MTACS/DopeConvos#134]
**Describe the bug**
Cannot change settings. Upon selecting a setting to change, such as Title or Background, I am met with only a black screen with that name on top.

**To Reproduce**
I restored RootOS once a couple weeks ago, then reinstalled the jailbreak and dopeconvos. It used to work.

**Expected behavior**
I’m supposed to be able to change the settings.

**Screenshots**
![0B011112-9309-489C-A774-5CE8758F8058](https://user-images.githubusercontent.com/34893229/88522997-d7d3ba80-cfbc-11ea-9e37-3805edf3e97b.png)
![1688A0A4-CA83-44C4-B740-934CEA3DB16F](https://user-images.githubusercontent.com/34893229/88523000-d86c5100-cfbc-11ea-806b-b2d1b8f6df52.png)

**Desktop (please complete the following information):**
- Device type: [iPhone 8+]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Zebra, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
