### ISSUE TITLE
Not working after Restoring Old Setup

### ISSUE THREAD

**Issue by SeaJayClark** [MTACS/DopeConvos#135]
**Describe the bug**
Unable to get any settings to work after using “Restore Old Setup” feature
**To Reproduce**
^
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
