### ISSUE TITLE
Keyboard>Send Button Coloring Edits Light And Dark Mode

### ISSUE THREAD

**Issue by LanceLePants** [MTACS/DopeConvos#136]
**Describe the bug**
Under Keyboard settings within DopeConvos and attempting to adjust Send Button colors in either Light or Dark mode views edits the coloring of both buttons for both modes instead of only the selected mode. 

**To Reproduce**
Change color for Send buttons. Switch to dark or light mode. Colors are modified for both and cannot be edited separately. 

**Expected behavior**
Editing Send Button colors in light mode should only affect light mode when selected, and vice versa.

**Screenshots**
![E42B06E8-A4F9-4FDF-B3A9-C633BBDEA09F](https://user-images.githubusercontent.com/69400017/89717549-4a5d7680-d97d-11ea-9861-ef92afd0a7a9.jpeg)

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro]
 - iOS Version: [13.5]
 - Package Manager: [Zebra]
 - Tweak Version: [3.3]

**Additional context**
unc0ver 5.3.1

**Comment by nahtedetihw** [comment]
resolved in 4.0
