### ISSUE TITLE
Entry View Buttons Setting

### ISSUE THREAD

**Issue by LanceLePants** [MTACS/DopeConvos#137]
**Describe the bug**
Entry View Buttons setting does not affect color of entry view buttons when modified and applied, in light mode, or dark mode. 

**To Reproduce**
Change color in Entry View Buttons setting in light or dark mode and select apply. Entry View Buttons remain unchanged. 

**Expected behavior**
Entry View Button settings should modify entry view buttons when applied. 

**Screenshots**
![9907E798-2276-4EF3-B80B-9934832E593A](https://user-images.githubusercontent.com/69400017/89717793-74179d00-d97f-11ea-8c27-83f7f821ca6b.jpeg)
![B571431F-E647-4F80-9B23-96C47F01E2DA](https://user-images.githubusercontent.com/69400017/89717794-74b03380-d97f-11ea-9757-86474ab8f712.jpeg)
![A11E4DBA-7457-4898-B6E2-ED35F692B023](https://user-images.githubusercontent.com/69400017/89717795-7548ca00-d97f-11ea-8280-f61b7d409261.jpeg)
![2D37F9CA-1AC0-4703-99F8-B4FD9C0FE97E](https://user-images.githubusercontent.com/69400017/89717796-75e16080-d97f-11ea-9e27-c8e423c6f0e0.jpeg)

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro]
 - iOS Version: [13.5]
 - Package Manager: [Zebra]
 - Tweak Version: [3.3]

**Additional context**
unc0ver 5.3.1

**Comment by nahtedetihw** [comment]
fixed in 4.0
