### ISSUE TITLE
Imessage and apple pay

### ISSUE THREAD

**Issue by boloaguirre** [MTACS/DopeConvos#138]
**Describe the bug**
When requested apple pay trough imessage it wont open apple pay nor neither if requested to to play imessage games for example with gamepigeon it wont open at all. But when uninstalling Dopeconvos they open normally 
**To Reproduce**
-Ask a friend to request to play imessage games or request amount of money trough imesssage with aplle pay
**Expected behavior**
-Neither nor game nor apple pay will open
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]iphone xs max
 - iOS Version: [ex. 13.3.1] 13.5
 - Package Manager: [ex. Zebra, Installer, Cydia]sileo and installer
 - Tweak Version: [Can be found at the bottom of the settings page] latest 3.3

**Additional context**

**Comment by nahtedetihw** [comment]
Please enable Disable Mask On Images in DopeConvos>Main Settings>Bubbles>Disable Mask On Images
