### ISSUE TITLE
DopeConvos

### ISSUE THREAD

**Issue by kraken8114** [MTACS/DopeConvos#139]
**Describe the bug**
Nothing will change reset everything and reinstalled and downgraded nothing seems to fix it 

**Expected behavior**
Wanted to make a new set up but nothing will change
- Device type: [iPhone 11 pro max]
 - iOS Version: [13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [3.3]

**Comment by nahtedetihw** [comment]
Resolved in 4.0
