### ISSUE TITLE
Background flickering when background gradient enabled

### ISSUE THREAD

**Issue by Aiirik** [MTACS/DopeConvos#14]
**Describe the bug**
When I enable background gradient, every time I sent a text it will flicker the background gradient over all the other messages . This stops if I disable the gradient. 

**To Reproduce**
Enable background gradient

**Expected behavior**
I’m sure it’s not supposed to flicker

**Screenshots**
Here is a video showing this : 

https://vimeo.com/409475663

**Desktop (please complete the following information):**
- Device type: iPhone X
 - iOS Version: 13.3.1
 - Package Manager: Zebra
 - Tweak Version: 1.1

**Additional context**
No additional information.

**Comment by nahtedetihw** [comment]
This has been fixed as of version 1.2 by disabling send animation
