### ISSUE TITLE
Not compatible with imessage games

### ISSUE THREAD

**Issue by Nanorithm** [MTACS/DopeConvos#141]
**Describe the bug**
Trying to play iMessage games (Game Pigeon) while using this tweak does not work, launching the messages app without the tweak loaded works.

**To Reproduce**
Launch app with tweak loaded, attempt to take a turn in a game

**Expected behavior**
Game runs normally

**Screenshots**

**Desktop (please complete the following information):**
- Device type: iPhone X
 - iOS Version: 13.2.2
 - Package Manager: Zebra
 - Tweak Version: 3.3

**Additional context**

**Comment by nahtedetihw** [comment]
Please enable Disable Mask On Images in DopeConvos>Main Settings>Bubbles>Disable Mask On Images
