### ISSUE TITLE
Different color for light/dark mode not working correctly 

### ISSUE THREAD

**Issue by alexmen14** [MTACS/DopeConvos#142]
**Describe the bug**
When in keyboard setting of light mode, changing the SMS send button color to a random color will change it, but going into de dark options same setting this random color will be there too, here i will not be able to choose a different color for light/dark mode, it will always overwrite one.

**To Reproduce**
Settings > DopeConvos >light options > keyboard > change color of sms send button

After go to dark options same place and same color will be there.

**Expected behavior**
Having the possiblity to have a different color for the send button for light or dark mode.

**Screenshots**

**Desktop (please complete the following information):**
- Device type: Iphone 11
 - iOS Version: 13.5
 - Package Manager: Zebra
 - Tweak Version: 3.3

**Additional context**

**Comment by nahtedetihw** [comment]
Issue resolved in 4.0
