### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by cjocollin** [MTACS/DopeConvos#147]
**Describe the bug**
When trying to change the background to an image, it won’t let me select a image to place

**To Reproduce**
Light/Dark Options->Background->Conversation/Chat Background->”Enable Conversation/Chat Background”

**Expected behavior**
Something to click to pick an image from my Photos

**Screenshots**
![FF096853-AA14-4248-A5CF-E07BCDC0CB40](https://user-images.githubusercontent.com/74850089/99896631-50dbd980-2c60-11eb-99ea-f2b66e309c2c.png)

**Desktop (please complete the following information):**
- Device type: iPhone 11
 - iOS Version: 13.5
 - Package Manager: Installer 5.1
 - Tweak Version: 4.1

**Additional context**
It works on DopeConvos 3.3, but stopped working on 4.0/4.1

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
