### ISSUE TITLE
Mask on Images

### ISSUE THREAD

**Issue by cjocollin** [MTACS/DopeConvos#148]
**Describe the bug**
I updated the tweak from 3.3 to 4.1 and I saw that chat backgrounds disappeared, so I downgraded back to 3.3, everything was back to normal, except for the “Disable Mask on Images.” It stopped disabling, so I upgraded back to 4.1 to see if it was just a glitch, it still didn’t work, so I tried to reset all prefs and “Disable Mask on Images” still wasn’t doing anything, I had to download a different tweak to help the issue.

**To Reproduce**
Main Settings->Bubbles->”Disable Mask on Images”

**Expected behavior**
Disabling the mask on the texts and images when a theme is applied.

**Screenshots**
![B2A02454-F346-40A6-95F0-9EC37FB864FE](https://user-images.githubusercontent.com/74850089/99896957-4ec74a00-2c63-11eb-8a64-bd8e136b02d8.png)
Sent a random message to myself to show

**Desktop (please complete the following information):**
- Device type: iPhone 11
 - iOS Version: 13.5
 - Package Manager: Installer 5.1
 - Tweak Version: 4.1

**Additional context**
I tried to downgrade from 4.1 to 4.0 to 3.3 to see if it will help, but nothing. Also tried uninstalling and reinstalling.

**Comment by nahtedetihw** [comment]
When using a UITheme, you need to go to DopeConvos>Main Setting>Bubbles>Gradient Bubbles>Enable UI Theming
