### ISSUE TITLE
Expand contact options. 

### ISSUE THREAD

**Issue by trivjedn00m** [MTACS/DopeConvos#15]
https://imgur.com/a/HR6JK6V
Expand contact options.  at the top.  they appear for a while, then turn gray to see them.
pohne x
iOS 13.3.1
Checkrain/cydia

**Comment by nahtedetihw** [comment]
Still have not been able to get this working, the options are tinted, but expanded they are using a UIVibrancyEffectView which overtakes the tint color. Will keep looking into this.

**Comment by nahtedetihw** [comment]
resolved in 4.0
