### ISSUE TITLE
Dope convos custom background image not working

### ISSUE THREAD

**Issue by cosmo100292** [MTACS/DopeConvos#150]
With background image selected it does not generate the image box to choose an image. I have tried with the stock dope preset as well as other presets with background images with no change. 

**To Reproduce**
Select background image

**Expected behavior**
Image selector should populate

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone 11 pro Max ]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Zebra, Sileo , Cydia]
 - Tweak Version: [4.1]

**Additional context**

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
