### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by triizzyyyy** [MTACS/DopeConvos#151]
**Describe the bug**
There’s nowhere to apply background images to the chats or conversations 

**To Reproduce**

**Expected behavior**

**Screenshots**

![EF8214C4-CB46-4B3C-BFCD-F0CA8DDADBCB](https://user-images.githubusercontent.com/64508199/99997852-be385900-2d8b-11eb-8acf-72e98cd6e3d3.png)
![13BE8E3A-DB2E-4DF0-9598-BC3699EEE298](https://user-images.githubusercontent.com/64508199/99997875-c5f7fd80-2d8b-11eb-81c2-35ae1ad10610.png)
![Uploading D07D6CC7-1870-4CE0-8FA9-8B3858EDEAA6.png…]()

**Desktop (please complete the following information):**
- Device type: iPhone 11 Pro Max
 - iOS Version: 13.5
 - Package Manager: Cydia
 - Tweak Version: 4.1

**Additional context**

**Comment by MTACS** [comment]
This was removed as it was incredibly buggy and relied on a third party library to pick the image. Images are now set in a theme bundle, to add tour own please refer the wiki for more information on creating a preset

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
