### ISSUE TITLE
Won’t let me change image. 

### ISSUE THREAD

**Issue by jperdomo35** [MTACS/DopeConvos#152]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
