### ISSUE TITLE
Seems to be totally broken now

### ISSUE THREAD

**Issue by price1979** [MTACS/DopeConvos#153]
**Describe the bug**
Missing most options. Can’t pick background image. Alpha. Etc. 

**To Reproduce**
Just install it. 
**Expected behavior**
A clear and concise description of what you expected to happen. Have options that I had previously 

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone Se v2]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page] all of them now. 

**Additional context**

**Comment by MTACS** [comment]
The option to set background images on chat and conversations has been moved to theme bundles. This is probably a inconvenience, but it was the reason why preferences were broken on previous versions

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
