### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by kyaam** [MTACS/DopeConvos#154]
**Describe the bug**
When attempting to add a background image, the option to select the image from a source is missing.

**To Reproduce**
Attempt to add a background image in either light or dark mode.
**Expected behavior**
The ability to add a background image.
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [4.1]

**Additional context**

**Comment by nahtedetihw** [comment]
Background Images are now loaded from the bundle. /Library/Application Support/DopeConvos/PRESETNAME.bundle

convolight.png
convodark.png
chatlight.png
chatdark.png
