### ISSUE TITLE
Doesn’t install with sileo or Cydia, time out!

### ISSUE THREAD

**Issue by JoelPeterPage** [MTACS/DopeConvos#156]
**Describe the bug**
A clear and concise description of what the bug is. If your bug is related to selecting images, this is intentional and done to improve stability. Please refer to the Wiki for more information. Any repeating bugs related to this issue will be deleted.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
make sure your device is registered on account.twickd.com and refresh sources
