### ISSUE TITLE
Cannot play message app game with dope convos enabled

### ISSUE THREAD

**Issue by levianthony** [MTACS/DopeConvos#16]
**Describe the bug**
I can start iMessage games like pool, darts, cup pong, etc but once it’s been started I cannot tap on it to play or respond.  I tap it and nothing happens.  When I disable dope convos in settings they work again. 

**To Reproduce**
Step 1: Start app game.  
Step 2: Once other player responds tap on game. 
Step 3: tap game to play your turn.
Step 4: nothing happens

**Expected behavior**
Game should open and allow me to play.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Device type: iPhone 11 Pro
 - iOS Version: ex. 13.3
 - Package Manager: Zebra and Cydia
 - Tweak Version: 1.1

**Additional context**
Just wanna play my games bruh! 🤪

**Comment by OVisuals** [comment]
Try disabling the bubbles I option. Can you play now?

**Comment by nahtedetihw** [comment]
He’s talking about outline bubbles option, if you disable that it should fix games
