### ISSUE TITLE
Conversation/App flicker

### ISSUE THREAD

**Issue by WorksbyBBS** [MTACS/DopeConvos#17]
**Describe the bug**
When I open a chat for the first time, the messages app/screen flickers

**To Reproduce**
Close Messages app completely. Open it, then open any conversation 

**Expected behavior**
App/conversation doesn’t flicker

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro]
 - iOS Version: [13.2.3]
 - Package Manager: [Zebra]
 - Tweak Version: [1.1]

**Comment by nahtedetihw** [comment]
This has been fixed in Version 1.7
