### ISSUE TITLE
Unread Notification Disappearing

### ISSUE THREAD

**Issue by mrdrummerboy97** [MTACS/DopeConvos#19]
**Describe the bug**
As soon as I enable the tweak and hit “Apply”, the standard, blue, unread indicator for my messages goes away whether I change any settings or reset to default, respring and apply.
![C8DB3C38-0C05-4960-82E2-C0CF70BFEF40](https://user-images.githubusercontent.com/62127852/79990185-bbd0f200-847e-11ea-9b79-a1f287d0dfe4.jpeg)
![FAC36791-D282-45ED-8E7B-464AD6F6619C](https://user-images.githubusercontent.com/62127852/79990193-becbe280-847e-11ea-9ff6-0d2717c2486e.jpeg)

**To Reproduce**
1.) Enable the tweak.
2.) Apply the tweak with standard settings.

**Expected behavior**
Up until the most recent update, this hadn’t happened. Only now are the stock unread notifications totally disappearing for unread messages as soon as I enable the tweak.

**Screenshots**

**Desktop (please complete the following information):**
- Device type: iPhone XS
 - iOS Version: 13.3
 - Package Manager: Zebra and Cydia
 - Tweak Version: Version 1.6

**Additional context**

**Comment by nahtedetihw** [comment]
This is not a bug, you need to activate the new unread, pinned, muted buttons in DopeConvos>Conversations

**Comment by mrdrummerboy97** [comment]
So, if we don’t want to use the indicator in the tweak for unread notifications, is there a way to just use the default stock one? Or is it just the indicator from the tweak?

**Comment by nahtedetihw** [comment]
Unfortunately no, the original indicator images caused issues with the new images so I had to hide the original ones.
