### ISSUE TITLE
Messages app crashing upon text entry

### ISSUE THREAD

**Issue by misfitskater6** [MTACS/DopeConvos#21]
**Describe the bug**
While the tweak is enabled, the Messages app crashes when typing in the reply field. Happens both for iMessages and SMS. Usually it will crash after typing only a few characters, but sometimes will take more than a few and then will crash. This started happening with version 1.2 I believe, I didn’t have this problem with version 1.1 or lower.

**To Reproduce**
Ensure the tweak is currently active and showing the changes in the Messages app, and start typing a message in a conversation and the app will crash.

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro Max
 - iOS Version: 13.3
 - Package Manager: Cydia
 - Tweak Version: 1.7

**Additional context**

**Comment by misfitskater6** [comment]
I've played around with the tweak settings, enabling and disabling things, resetting and starting over from scratch, and it seems like this crash is only happening when App Tint Color is enabled. So far I haven't had any Messages app crashes with that setting disabled.

**Comment by nahtedetihw** [comment]
This has been fixed and will be released in the next version.
