### ISSUE TITLE
Images aren’t displaying properly 

### ISSUE THREAD

**Issue by kegobass** [MTACS/DopeConvos#28]
Issue: when texting a picture to someone, I get a blob of color (see screenshot). 

**To Reproduce**
Copy picture, paste into text message, send

**Expected behavior**
Image should display properly. 

*screenshot*

https://i.imgur.com/AURLaqY.jpg

**Desktop (please complete the following information):**
- Device type: iPhone X
 - iOS Version: 13.4.1
 - Package Manager: Zebra
 - Tweak Version: 2.0

**Additional info**

UI theming option is enabled. This worked on previous versions.

**Comment by kegobass** [comment]
Another screenshot just doesn’t show the image at all. 

https://i.imgur.com/OyvrJTV.png

**Comment by nahtedetihw** [comment]
I'm not able to reproduce this issue. It might be your UI Theme, try to turn on Disable Mask on Images in DopeConvos>Bubbles

**Comment by kegobass** [comment]
That did the trick, thanks!!
