### ISSUE TITLE
Nav Bar Blocking

### ISSUE THREAD

**Issue by OVisuals** [MTACS/DopeConvos#29]
**Describe the bug**
Nav bad blocks the first text message when scrolling down sometimes or opening the app again

**To Reproduce**
Open the back and swipe down or up. Reopen the app and sometimes the nav bar is already blocking the first message 

**Expected behavior**
Not to block the first message and even out if the search bar is selected to be hidden.

**Screenshot**
https://youtu.be/wm0FQE29K9Q

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [Cydia]
 - Tweak Version: [2.1]

**Comment by nahtedetihw** [comment]
This has been fixed in 2.2
