### ISSUE TITLE
Conversation list bug

### ISSUE THREAD

**Issue by levianthony** [MTACS/DopeConvos#30]
**Describe the bug**
In conversation list the top conversation is covered by the header and you cannot access it. I keep pulling down and it just covers it again. 

**To Reproduce**
1) open messages
2) ensure you are on the conversation list screen.
3) scroll to the top
4) you will see too conversation cannot be selected and is being the header 

**Expected behavior**
To be able to access all conversations easily 

**Screenshots**

https://imgur.com/a/rsyi4n2

**Desktop (please complete the following information):**
- Device type: iPhone 11 pro
 - iOS Version: 13.3
 - Package Manager: Zebra and Cydia
 - Tweak Version: 2.1

**Additional context**

**Comment by nahtedetihw** [comment]
This has been fixed as well in latest version?

**Comment by levianthony** [comment]
Yup, fixed.

**Comment by nahtedetihw** [comment]
Awesome, thanks again!
