### ISSUE TITLE
Hide convos from a specified contact

### ISSUE THREAD

**Issue by itsshabby** [MTACS/DopeConvos#31]
**Describe the feature you'd like to be added**

Hey man how’s it going honestly the main reason I bought this tweak was I thought you would be able to hide a text convo with a specific person.  (Example- my ex keeps playing mind games with me and I want to be able to hide and unhinged texts from her if I don’t want to see them but still have them just in case.). Please let me know if that’s possible!  I still am keeping the tweak because it’s amazing!  Thank you again for making it

**Comment by nahtedetihw** [comment]
iDunnoU can do this. Not sure if this will be implemented into DopeConvos
