### ISSUE TITLE
GamePidgeon

### ISSUE THREAD

**Issue by Starshooter1996** [MTACS/DopeConvos#32]
**Describe the bug**
If someone is to send a game from GamePidgeon you cannot interact with it. You are able to react to it but touching it does not open the game.

**To Reproduce**
If someone sends a message with a game from GamePidgeon it will not open.

**Expected behavior**
The game is supposed to open and be playable. As when launching with no tweaks it interacts just fine.

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [13.3]
 - Package Manager: [Zebra, Cydia]
 - Tweak Version: [2.1]

**Comment by nahtedetihw** [comment]
Try to turn on Disable Mask On Images in DopeConvos>Bubbles
