### ISSUE TITLE
Search disable bug

### ISSUE THREAD

**Issue by chetz87** [MTACS/DopeConvos#34]
**Describe the bug**
When we disable search bar and search background there is a weird looking navigation bar that shows up covering few conversations on the top. It also happens wen u scroll all the way to the top. It gets fine when search is enables 

**To Reproduce**
Disable search in more options

**Expected behavior**

**Screenshots**

![03BAED88-244E-4040-BFDC-840E34A898AB](https://user-images.githubusercontent.com/65161305/81545851-277bf000-9397-11ea-9bda-8edc6909ee3a.png)
![03759B10-FE9E-41B6-9800-C31E3D777CAD](https://user-images.githubusercontent.com/65161305/81545899-3662a280-9397-11ea-8bf4-ad2ecc72ea94.png)

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro Max]
 - iOS Version: [ex. 13.3]
 - Package Manager: [Cydia]
 - Tweak Version: [1.1]

**Additional context**

**Comment by nahtedetihw** [comment]
This was an attempt at removing the uneeded space when hiding the search bar, but it did not work very well. I believe the issue has been resolved in recent version correct?

**Comment by chetz87** [comment]
Yes looks like it’s sorted
