### ISSUE TITLE
Background image in conversation makes app crash

### ISSUE THREAD

**Issue by frswilliam** [MTACS/DopeConvos#35]
**Describe the bug**
When having a background image enabled in the conversation if you receive/send 3-4 messages in succession it will lag then crash the app. 

**To Reproduce**
Simply try and have a background enabled in the conversation and just send yourself 3-4 messages quickly. Tried this and made my app crash. Went back and disabled the background image and sent around 10 messages to myself quickly and didn’t crash at all or lag.

**Expected behavior**
Was just expecting this to not be an issue, but hopefully it can be fixed.

**Desktop (please complete the following information):**
- Device type: [iPhone XR]
 - iOS Version: [ex. 13.3]
 - Package Manager: [Cydia]
 - Tweak Version: [2.2]

**Comment by nahtedetihw** [comment]
Can you confirm if this issue still occurs in version 2.5?

**Comment by frswilliam** [comment]
Hello, yes. I just updated to 2.5 and it seems to still crash for me.

**Comment by nahtedetihw** [comment]
I believe this isn't due to the Background image but due to AutoCorrect, Do me a favor and try enabling Predictive Bar from Settings>General>Keyboard

**Comment by frswilliam** [comment]
I think you’re right, that seems to be the case. definitely didn’t crash like before. Is there a way to fix it so I don’t need the predictive option on?

**Comment by nahtedetihw** [comment]
I will try and work on a fix for this issue but for now you will need to re-enable Predictive Bar in order to avoid crashes.

**Comment by frswilliam** [comment]
Okay I appreciate it, thank you. :)
