### ISSUE TITLE
Had to downgrade, Dope Convos Crashing

### ISSUE THREAD

**Issue by levianthony** [MTACS/DopeConvos#36]
**Describe the bug**
On the latest version Dope Convo just crashes and my messages go back to stock form.  This happens on every screen and it’s random. Had to downgrade it was so bad. ( I also haven’t changed any of my settings. Haven’t turned on any of the new features)

**To Reproduce**
Open messages and do whatever you want. Wait or send a message, it will happen eventually. (Well for me at least)

**Expected behavior**
Dope Convos to stay applied.

**Screenshots**

**Desktop (please complete the following information):**
- Device type: iPhone 11 pro
 - iOS Version: 13.3
 - Package Manager: Zebra and Cydia
 - Tweak Version: 2.2 

**Additional context**

**Comment by nahtedetihw** [comment]
Does the issue still occur in 2.5?

**Comment by levianthony** [comment]
It hasn’t yet.  Everything is working good for me.

**Comment by nahtedetihw** [comment]
Thanks, sorry for the issues
