### ISSUE TITLE
version 2.2 bugged

### ISSUE THREAD

**Issue by samwllson9478** [MTACS/DopeConvos#38]
**Describe the bug**
After updating to this version I keep experiencing the switches/toggles turning on and off without me touching them
**To Reproduce**
Download version 2.2
**Expected behavior**
Toggles will turn on and off making it difficult to customize
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by trevor579** [comment]
I’m having the same issue on iPhone XR with iOS 13.4.1

**Comment by nahtedetihw** [comment]
resolved in 4.0
