### ISSUE TITLE
Can’t get the bubbles to work. iPhone 7+ IOS 13.3.1 I can’t get the bubbles to show a specific color I can get them to be outlined but can’t make them a different color. It’s just the background color

### ISSUE THREAD

**Issue by JaCrissspy** [MTACS/DopeConvos#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
Please send a tweak list

**Comment by JaCrissspy** [comment]
[cid:98E59179-7E8F-41E8-B08F-3DD1947DD18E-L0-001][cid:CAF00CB2-8C6F-4ACE-9068-7824A982B83F-L0-001]

Sent from my iPhone

On Apr 21, 2020, at 9:21 PM, ETHN <notifications@github.com> wrote:

﻿

Please send a tweak list

**Comment by nahtedetihw** [comment]
What is that?

**Comment by JaCrissspy** [comment]
My tweak list

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nahtedetihw** [comment]
[cid:98E59179-7E8F-41E8-B08F-3DD1947DD18E-L0-001][cid:CAF00CB2-8C6F-4ACE-9068-7824A982B83F-L0-001]

That's all I see
