### ISSUE TITLE
Change text color from messages main menu 

### ISSUE THREAD

**Issue by htb723** [MTACS/DopeConvos#44]
Would it be possible to add a feature to change The color of the text messages as they appear in the main menu? Seen in the following red circled item:

![B10086D3-5FAF-4482-92AD-E581BB51C12E](https://user-images.githubusercontent.com/42898475/82832333-9d8c5680-9e6f-11ea-8855-7f86f3ed1a87.jpeg)

Thanks!

**Comment by nahtedetihw** [comment]
DopeConvos>Conversations>Custom Preview Color
