### ISSUE TITLE
Can't getDopeConvos Tweak working..

### ISSUE THREAD

**Issue by multycrime** [MTACS/DopeConvos#46]
I've just bought DopeConvos on Cydia
Installed it but cant get tweak work even i try reinstalling or respringing too many times. I thouht i should tell developer about the bug.

I'm using IPhone 11 Pro On ios 13.5 

- Device type: [iPhone 11Pro]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [2.7]

username: multycrime

**Comment by pschroeder89** [comment]
Same here. Applying my changes causes a respring but the Messages app never updates
