### ISSUE TITLE
Keyboard disappears 

### ISSUE THREAD

**Issue by JaCrissspy** [MTACS/DopeConvos#5]
**Describe the bug**
When ever I send a message the message does its little animation thing and the keyboard disappears until it is done sending. It’s really annoying when your trying to type fast 

**To Reproduce**
Just send a message
**Expected behavior**
Thought the keyboard wouldn’t disappear 
**Screenshots**
A screen recorded problem https://imgur.com/gallery/WzIPNpb
I’m going to also give you my settings to see if it’s my fault and if it is Please get back to me @ arguingsquid@outlook.com

**Desktop (please complete the following information):**
- Device type: [iPhone 7+]
 - iOS Version: [13.3.1]
 - Package Manager: [installer]
 - Tweak Version: [Can be found at the bottom of the settings page]
1.1
**Additional context**
![2B09F556-A38F-46BE-907A-146F13F0AB15](https://user-images.githubusercontent.com/62623829/79072484-3ba4d280-7caf-11ea-8df4-b8d4bf949f90.jpeg)
![DA3A382E-24ED-48EE-8417-3C90871E3D3D](https://user-images.githubusercontent.com/62623829/79072485-3c3d6900-7caf-11ea-8c31-112379d903b1.jpeg)
![7ED26820-75AE-4698-9644-9E18705CB66B](https://user-images.githubusercontent.com/62623829/79072486-3cd5ff80-7caf-11ea-9e91-52255f486ed2.jpeg)
![29FD1FA2-1418-43D1-98E1-53E00D9829F0](https://user-images.githubusercontent.com/62623829/79072489-3d6e9600-7caf-11ea-9d37-ffde279dd783.jpeg)
![24975A30-30AB-4AA4-8518-4732779DED07](https://user-images.githubusercontent.com/62623829/79072491-3e072c80-7caf-11ea-87b9-6ff671edda2e.jpeg)
![100B88D9-E5BD-4F4C-84F6-D35212EEE2B8](https://user-images.githubusercontent.com/62623829/79072493-3e072c80-7caf-11ea-9ede-b4e780cd425c.jpeg)
![2EEC971B-E798-48AA-82A2-D19341B7191E](https://user-images.githubusercontent.com/62623829/79072494-3e9fc300-7caf-11ea-82b5-d96000741dcb.jpeg)

**Comment by MTACS** [comment]
Fixed in 1.2
