### ISSUE TITLE
1 second delay on icons when opening convos

### ISSUE THREAD

**Issue by ochbob** [MTACS/DopeConvos#50]
Hello,

I bought DopeConvos, really love it.
But something weird happen, there is a kind of delay when opening convos, the two surrounded icons appear 1 second after.
No issue when I disable DopeConvos.

![iOS_13_keyboard_dedicated_emoji_key](https://user-images.githubusercontent.com/16723954/82898912-5c24a580-9f5a-11ea-8bcf-ed6153820f48.jpg)

**To Reproduce**
Enable DopeConvos, and open up a message conversation.

**Expected behavior**
No delay with the two surrounded icons when opening message conversation when DopeConvos is enable.

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro Max]
 - iOS Version: [13.5]
 - Package Manager: [Zebra and Cydia]
 - Tweak Version: [2.7]

Thank you !

**Comment by nahtedetihw** [comment]
This bug is due to a black transition that showed up underneath the entire keyboard when transitioning into a conversation. In order to remove that, this bug occurs.

**Comment by ochbob** [comment]
Thank you, so what should I do to fix this ?
Any workaround ? Or we need to wait a fix from your side ?

**Comment by ochbob** [comment]
Last update (2.9) fix this,

Thank you :)
