### ISSUE TITLE
No notifications on list

### ISSUE THREAD

**Issue by seangwns21** [MTACS/DopeConvos#51]
**Describe the bug**
Am on iOS 13.5 unc0ver and when I see a number on messages indicating unread messages, I go inside to the list view , to see no blue dot showing me which message is unread
**To Reproduce**
None. It just is that way for both me and my girlfriend 
**Expected behavior**
For it to work
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X] X
 - iOS Version: [ex. 13.3.1] 13.5
 - Package Manager: [ex. Zebra, Installer, Cydia] Zebra
 - Tweak Version: [Can be found at the bottom of the settings page] 2.7

**Additional context**

**Comment by nahtedetihw** [comment]
You need to activate the pinned, dnd and unread images located in DopeConvos>Conversations
