### ISSUE TITLE
Notifications Bug

### ISSUE THREAD

**Issue by kevinbarnettjr** [MTACS/DopeConvos#53]
**Describe the bug**
Messages shows a notification badge. Messages doesn’t show the badge under specific contact (The Blue Bubble) and crashed to safemode when I clicked to find out who sent new message. 

**To Reproduce**
In this example I got a notification from Amazon about a shipment via text. I have it set to “hide alerts” but the behavior seemed to cause a crash. I’m using default settings only changed SMS bubble color. 

**Expected behavior**
A badge on Messages Icon that doesn’t alert me (except visually) and a blue circle on the contact to signify a new message. 

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone XR]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [2.7]

**Additional context**

**Comment by nahtedetihw** [comment]
I think you need to turn on the DND indicator image in DopeConvos>Conversations

**Comment by kevinbarnettjr** [comment]
I did eventually discover that setting with the help of someone on r/jailbreak. There was another tweak that was causing a respring with this tweak but I removed the other one. Thanks!
