### ISSUE TITLE
Importing presets is extremely awkward/not possible

### ISSUE THREAD

**Issue by strafe** [MTACS/DopeConvos#56]
**Describe the bug**
Importing presets appears to be extremely awkward and sometimes not possible at all(?). This is due to their massive size and only being able to paste them into DopeConvos as text.

**To Reproduce**
1. Attempt to import [this](https://www.dropbox.com/sh/yuy73kre919777g/AAADQEdOHOZPW8Pc_-6_ul6Ka?dl=0&preview=CandyBites_DopeConvos.txt) preset.
2. Struggle as many apps crash while trying to select the entire text.
3. Possibly get it on your clipboard and paste it into the import dialog, to be told it is incomplete.

**Expected behavior**
Importing should be a hassle free process with no crashes or workarounds involved.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Device type: iPhone 11 Pro
 - iOS Version: 13.5
 - Package Manager: Zebra
 - Tweak Version: 2.7

**Additional context**
The option to import presets from a file instead, or some optimisation of how the config is serialized would be great.

**Comment by kuangwoo** [comment]
I second this. Couldn’t make import happen.

**Comment by nahtedetihw** [comment]
Use Files app

**Comment by nahtedetihw** [comment]
resolved in 4.0
