### ISSUE TITLE
Masks disabled for link previews regardless of settings

### ISSUE THREAD

**Issue by trevor579** [MTACS/DopeConvos#57]
**Describe the bug**
All link previews in messages have square corners regardless of whether or not you have “disable image masks” on. 

**To Reproduce**
1. Send a link in messages
2. See that the link does not have rounded corners

**Expected behavior**
I would expect the corners to be rounded on link previews. 

**Screenshots**
![D8F47978-81E9-4282-84A4-5E5077F366FB](https://user-images.githubusercontent.com/56181119/83299835-c84a1800-a1ab-11ea-9ce8-7eaa99425010.jpeg)

**Desktop (please complete the following information):**
- Device type: iPhone XR
 - iOS Version: 3.4.1
 - Package Manager: Zebra
 - Tweak Version: 2.7

**Comment by nahtedetihw** [comment]
resolved
