### ISSUE TITLE
Background on message list is black though transparency Set

### ISSUE THREAD

**Issue by D-elias** [MTACS/DopeConvos#58]
On the iPhone XS max on iOS 13.5, I have the text set to the largest size and my background image is not able to be viewed because a black background is covering it.  I need the text  to be large but I would like a transparent even though I have it set, it still shows a black background, when I make the text smaller in settings the font size affects it and it becomes transparent once the text is made small.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by D-elias** [comment]
DopeConvos 2.7 on Cydia
![90EE1A3F-0B7C-46A1-B4ED-6994AEC82464](https://user-images.githubusercontent.com/3038757/83317814-ac6f6200-a1fd-11ea-9f5d-595059290564.jpeg)
![D94177C9-7CA6-47D1-B454-AA531D034D19](https://user-images.githubusercontent.com/3038757/83317818-ada08f00-a1fd-11ea-82f9-43a2d13c9753.jpeg)

**Comment by nahtedetihw** [comment]
Why on earth would you have your text that giant? Obviously that is going to cause issues

**Comment by D-elias** [comment]
Because I  Need it to be large in order to see it.
