### ISSUE TITLE
Autocorrect pop up not showing. 

### ISSUE THREAD

**Issue by vikemosabe** [MTACS/DopeConvos#59]
**Describe the bug**
When typing in messages the autocorrect pop up does not display. 
Turning dopeconvos off brings it back. 

**To Reproduce**
Steps to reproduce the behavior: turning dopeconvos on. 

**Expected behavior**
Normal autocorrect 

**Screenshots**
[Video](https://www.dropbox.com/s/8neda9k7coe6d3r/2020-06-01%2020.29.47.mp4?dl=0) 

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro Max]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [2.7]

**Additional context**

**Comment by nahtedetihw** [comment]
Autocorrect caused a crash with DopeConvos so it had to be removed. Autocorrect still works when you type something wrong and press space, it will still autocorrect. You can also enable the prediction bar again (in Messages Settings) to get back autocorrect functionality.

**Comment by vikemosabe** [comment]
Enabling the suggestion bar will restore autocorrect?
Do I have to leave it turned on?
I don’t use suggestions and don’t want suggestions, only the autocorrect. 

Also, I did realize it still does the autocorrect, but without the tooltip I can’t tell when it’s about to change something. 
Has caused several miscommunications when I didn’t realize what was happening. 
All in all I enjoy the tweak, with this single exception. 
Are you planning to work on a fix for this, or is it low priority?
Thanks
