### ISSUE TITLE
Remove message typing  Indicators

### ISSUE THREAD

**Issue by D-elias** [MTACS/DopeConvos#60]
Add the option to remove message typing indicators to let the other person know you’re typing

**Comment by nahtedetihw** [comment]
I'm very confused by this. If you remove the typing indicator, that would have nothing to do with letting the other person know you're typing.

**Comment by D-elias** [comment]
There was a tweak years ago called MessageTypingIndicators and I was hoping  you could implement this  as a feature.
With this tweak you can get rid of the ability for others to be notified you are typing in iMessages. A feature Apple forgot to include with the Messages app.

**Comment by nahtedetihw** [comment]
This feature has been completed in version 3.0, no ETA yet
