### ISSUE TITLE
Recommended presets

### ISSUE THREAD

**Issue by metaljay** [MTACS/DopeConvos#61]
Just purchased this, little overwhelmed with the sheer amount of customisation (which is a good thing), it would be useful it you had suggested presets based on other setups or ones you recommend.
The ones you have used in the trailer are a good start or even just a simple dark mode improver?

**Comment by thehappydinoa** [comment]
Ya I am having this same issue, I tried to import ColorizedChat setup without any luck. Would love to see a wiki page on it.

**Comment by nahtedetihw** [comment]
There is a wiki page on DopeConvos. Look in the package Description for the information you need.

**Comment by nahtedetihw** [comment]
Preloaded Presets are coming in version 3.0, no ETA yet
