### ISSUE TITLE
Text entry/app bar delayed

### ISSUE THREAD

**Issue by justeaton** [MTACS/DopeConvos#64]
**Describe the bug**

Upon opening a iMessage, the app bar/text field are visible in the last-closed conversation, as normal. When changing to another conversation, that text entry/app bar appear with a noticeable delay.

**To Reproduce**

Swipe/tap back to the conversation list, open a different conversation. I’ve disabled all add-ons (sans DopeConvos) with iCleaner Pro, with the issue persisting, also tried downgrading a version. On my stock iPhone 8 (13.5) the field loads/appears with the conversation with each swipe.

**Expected behavior**

No text field/app bar pop-in when switching between conversations.

**Screenshots**

Excuse my lazy mark-up; the “pop-in” is ~1s delay so I couldn’t time the screenshot. The piece below that blue line pops up later than the remaining content. 

https://ptpimg.me/9oa742.jpg

**Desktop (please complete the following information):**

- Device type: iPhone SE 2
 - iOS Version: 13.5
 - Package Manager: Cydia
 - Tweak Version: 2.8

**Comment by Asheque** [comment]
I just submitted the same bug and a video to the developer. You definitely explained it much better than I could. Sadly, I had to turn off the tweak. Ruined the iMessage experience.

**Comment by nahtedetihw** [comment]
This issue was fixed in version 2.9
