### ISSUE TITLE
iMessage bottom typing bar appearing slow.

### ISSUE THREAD

**Issue by Asheque** [MTACS/DopeConvos#65]
Every time I select a conversation the bottom bar is missing then few second later it will appear.

If I return to Homescreen and enter iMessage the bottom bar is still there if I’m still on same conversation. But if I return to list and select another conversation then bottom bar is delayed again. Kinda getting annoying.

**To Reproduce**
Enabling DopeConvo is causing it. All other settings are on default.

**Desktop (please complete the following information):**
- Device type: [iPhone XS Max]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [2.8]

Please kindly look into it. Really want to use it otherwise I have no choice but to uninstall it. I just purchased it 3 hours ago.

**Comment by nahtedetihw** [comment]
I believe this was fixed in version 2.9
