### ISSUE TITLE
No background image even though settings are on

### ISSUE THREAD

**Issue by kuangwoo** [MTACS/DopeConvos#68]
**Describe the bug**
Background image doesn’t appear even though image is selected, settings are on and applied with respring. 

**To Reproduce**
Turn background image usage On, select an image, respring.

**Expected behavior**
Background image should appear.

**Screenshots**
![9B061DDE-DFFA-48C3-8481-F0C2FE0A4C3A](https://user-images.githubusercontent.com/62356622/83934417-20e86900-a7db-11ea-9502-9b74764bb6e5.jpeg)
![1ECEF6D0-0575-4243-9647-4A4653B7A52E](https://user-images.githubusercontent.com/62356622/83934422-2a71d100-a7db-11ea-95ec-54dedbaef565.png)

**Desktop (please complete the following information):**
- Device type: iPhone 11 Pro Max
 - iOS Version: 13.5
 - Package Manager: Cydia
 - Tweak Version: 2.8

**Comment by nahtedetihw** [comment]
Disable the table view bg color at the bottom of DopeConvos>Conversations. You background image is there, but the table view bg color is applied on top of it.
