### ISSUE TITLE
Issue with background image

### ISSUE THREAD

**Issue by bbbbbbora** [MTACS/DopeConvos#69]
**Describe the bug**
After you apply a background image for the conversation, you cannot change it. If you set a new image, it always shows the original image.

**To Reproduce**
Change the background image from the original one.

**Expected behavior**
The new image should be seen in the conversation

**Screenshots**

**Desktop (please complete the following information):**
- Device type: 11 Pro
 - iOS Version: 13.5
 - Package Manager: Cydia
 - Tweak Version: 2.8

**Additional context**

**Comment by nahtedetihw** [comment]
resolved in 4.0
