### ISSUE TITLE
“Exact Time”

### ISSUE THREAD

**Issue by Oxycodon-IV** [MTACS/DopeConvos#70]
**Describe the feature you'd like to be added**

Simple add more detail into the “Time” stamp of each conversation like the tweak “ExactTimeMessages” built into dopecovos to look like the image attached.

![FCEE3857-BBC4-4B4F-9511-DC1C06E4B50C](https://user-images.githubusercontent.com/20485643/83947665-bbb36880-a818-11ea-83ed-3df37557be40.png)

**Comment by nahtedetihw** [comment]
this request has been completed
