### ISSUE TITLE
iMessage bar delay

### ISSUE THREAD

**Issue by mateow99** [MTACS/DopeConvos#71]
**Describe the bug**
The bar at the bottom of imessage has a delay when entering a convo and is gone when transitioning from convo to main screen. I disabled every setting in dopeConvos except for it being enabled and it still happened. 

**To Reproduce**
I just noticed it and I can’t get rid of it, did nothing to make it do this. 

**Expected behavior**
The bar at the bottom is not supposed to disappear but instead animate with the convo together. 

**Screenshots**
[Screen recording of issue](https://imgur.com/gallery/ZHMvhyg) 

**Desktop (please complete the following information):**
- iPhone 11
 - 13.5
 - Cydia
 - Tweak Version: 2.8

**Comment by nahtedetihw** [comment]
I believe this was fixed in version 2.9
