### ISSUE TITLE
IMessage lag

### ISSUE THREAD

**Issue by giannakillz** [MTACS/DopeConvos#73]
**Describe the bug**
When you open a conversation in iMessages the bottom bar where you type/press send/open apps/games etc.. has a 1-2 second lag before it pops up. Doesn’t happen when dopeconvos is turned off and iMessages is back to stock. 

**To Reproduce**
Open a conversation look at the bottom to see if there is a lag in the space where you type. 

**Expected behavior**
No lag when opening a conversation, should open along side the rest of it seamlessly.  

**Desktop (please complete the following information):**
- Device type: [iPhone 8 plus]
 - iOS Version: [ex. 13.5]
 - Package Manager:  [Cydia]
 - Tweak Version: [2.8]

Also would like to add I’m using the reva UI theme from Packix.

**Comment by nahtedetihw** [comment]
I believe this was fixed in version 2.9
