### ISSUE TITLE
No background when composing new message 

### ISSUE THREAD

**Issue by Shoelace22** [MTACS/DopeConvos#74]
**Describe the bug**
When composing a new message there will be no background. It is just the main page with all the conversations with the place to type in the new number and keyboard but where the message should be is invisible.  Even when typing out the number of someone previously contacted and you usually see old messages the old messages will come but still on the background of the main messages page. 

**To Reproduce**
Steps to reproduce the behavior: Go into messages.

Click compose message. 

For previous contact type out contact name and click contact. 

**Expected behavior**
What I expect is to go into a new message with a blank background or even previous conversation if I messaged them before. 

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone 11 plus max]
 - iOS Version: [ex. 13.5]
 - Package Manager: [Cydia]
 - Tweak Version: [2.8]

**Additional context**
![E71770E9-F8BB-4D51-8354-E78C1185B8CD](https://user-images.githubusercontent.com/65961811/84035590-9716d800-a961-11ea-9b19-0becdf86a01c.png)
![6124CB88-AC2D-4BBE-982D-EB7385F54C61](https://user-images.githubusercontent.com/65961811/84035616-a3029a00-a961-11ea-8d03-9160cd2b3529.png)

**Comment by nahtedetihw** [comment]
I believe this was fixed in version 2.9
