### ISSUE TITLE
Most of the settings do not work and effect change I can toggle the switch but that’s it 

### ISSUE THREAD

**Issue by gmanc2** [MTACS/DopeConvos#75]
**Describe the bug**
Only a few of the settings selections produce visible results
**To Reproduce**
Download the app I enabled almost every setting and it still does not show. 
**Expected behavior**
Show the settings I changed 
**Screenshots**

Screen cap of messages  and settings 
![61A1F1C0-E521-46FF-B2FD-36170BA88B83](https://user-images.githubusercontent.com/4944080/84065998-461fd780-a993-11ea-9617-9b1d630a05ce.png)
![A32A6AEF-AEBA-4619-AB83-D6FF89836B70](https://user-images.githubusercontent.com/4944080/84066535-17563100-a994-11ea-95c8-3de7aeff1f38.png)
![E3240E43-9A3D-4C4E-84C9-8D299ED6E143](https://user-images.githubusercontent.com/4944080/84066541-19b88b00-a994-11ea-899b-a74a75f2ac5c.png)
![8FF065CC-51B0-45CA-9B80-967E49B52AA6](https://user-images.githubusercontent.com/4944080/84066543-1a512180-a994-11ea-8df5-a2ae71edbf57.png)
![8A16A9D2-9FFC-41A4-BA6C-A41D276983B6](https://user-images.githubusercontent.com/4944080/84066545-1a512180-a994-11ea-8156-e57692adee33.png)
![A6D158C2-1336-417B-9847-28ACF69D2DD5](https://user-images.githubusercontent.com/4944080/84066547-1ae9b800-a994-11ea-8e1c-191c141ac260.png)
![7E59B626-1D46-457B-ABBE-0E529CD2A2BB](https://user-images.githubusercontent.com/4944080/84066548-1ae9b800-a994-11ea-9bfe-7ff4fd106a09.png)

**Desktop (please complete the following information):**
- Device type: [iPhone X]
iPhone XS Max
 - iOS Version: [ex. 13.3.1]
13.5
 - Package Manager: [ex. Zebra, Installer, Cydia] 
Zebra and cydia
 - Tweak Version: [Can be found at the bottom of the settings page]
2.8

**Additional context**
The title changing also works but that’s about it

**Comment by nahtedetihw** [comment]
resolved in 4.0
