### ISSUE TITLE
SMS Filter, Auto Answer And Hide..

### ISSUE THREAD

**Issue by multycrime** [MTACS/DopeConvos#76]
**I would suggest that, maybe you could add A Real and working “Spam-Betting SMS Filter” and “Auto answer” and “Hide-Unhide  Conversation” options to DopeConvos. That will be really useful for all of users. **
Thank you for your interest ✌️

**Comment by nahtedetihw** [comment]
I would suggest Iris tweak. Since that exists, we will not be adding this feature.
