### ISSUE TITLE
Change settings within Dope Convos, nothing happens upon respring.

### ISSUE THREAD

**Issue by levianthony** [MTACS/DopeConvos#77]
**Describe the bug**
this is multiple bugs in my opinion.  I have a preset saved and have been using it for a while. it's a preset I created.  If I change any, I mean any settings in dope convos....nothign changes my preset stays.  I deleted the preset, nothing changes.  I used the reset settings option, nothing changes.  I deleted dope convos and reinstalled nothing changes. I manually deselected every toggle in dope convos, not only do some reset back on after a respring but nothing changes in my messages app, still full dope convos settings I had originally.  All I want to do is set the background image and blur it. can't even do that. when I set the background image, the background changes to a grey color. not even my original color. 

**To Reproduce**
Steps to reproduce the behavior: Step 1- change anything in dop convos
Step 2: respring
Step 3: scream at the top of your lungs because you cannot customize the customizable tweak! haha jk, but for reals

**Expected behavior**
let me make changes freely. let me set my background image and blur the damn thing.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Device type: iPhone 11 Pro
 - iOS Version: 13.5
 - Package Manager: Zebra and Cydia
 - Tweak Version: 2.8

**Additional context**

**Comment by nahtedetihw** [comment]
This issue has been resolved in version 3.0, no ETA yet
