### ISSUE TITLE
Reset settings does nothing

### ISSUE THREAD

**Issue by kuangwoo** [MTACS/DopeConvos#78]
**Describe the bug**
So I was so frustrated that Background image won’t load and then all of a sudden load, and then I wanted to turn it off it won’t, and this happens with almost all settings, it’s a hell to properly apply any color or background image or blur, and so I did a reset settings, and then respring, and then reset once more, and respring, my message app looks the same as before reset. All toggles stay on, colors and gradients are untouched, selected bg image still there.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone 11 Pro Max
 - iOS Version: [ex. 13.5
 - Package Manager:  Cydia]
 - Tweak Version: 2.9

**Additional context**

**Comment by nahtedetihw** [comment]
This issue has been resolved in version 3.0, no ETA yet
