### ISSUE TITLE
Game Pigeon doesn’t open with DopeConvo

### ISSUE THREAD

**Issue by OVisuals** [MTACS/DopeConvos#8]
**Describe the bug**
When the tweak is enabled you aren’t able to open a game pigeon message to play with your friends for whatever reason

**To Reproduce**
Steps to reproduce the behavior: enable tweak and try to play a game, no matter how much you click it doesn’t open

**Expected behavior**
Open the game to play it

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [Cydia]
 - Tweak Version: [1.1]

**Additional context**

**Comment by nahtedetihw** [comment]
This has been tested and works fine.

**Comment by OVisuals** [comment]
I have made a video we’re i used icleanerpro to disable al other tweaks to make sure nothing else is conflicting. I then started to disable stuff from DopeConvo until I could open it and turns out bubbles is causing the issue I made a small video so you can se what I’m talking about https://youtu.be/XWq71JzQ7d8

**Comment by OVisuals** [comment]
> This has been tested and works fine.

I have made a video we’re i used icleanerpro to disable al other tweaks to make sure nothing else is conflicting. I then started to disable stuff from DopeConvo until I could open it and turns out bubbles is causing the issue I made a small video so you can se what I’m talking about https://youtu.be/XWq71JzQ7d8

**Comment by nahtedetihw** [comment]
I’ve added a toggle for disabling mask on images, this should be fixed as of version 1.6

**Comment by OVisuals** [comment]
Awesome, just tried it and it works now. Sucks the images are a bit edged but oh well. Thank you
