### ISSUE TITLE
Custom colors on bubbles don’t change

### ISSUE THREAD

**Issue by td-boop** [MTACS/DopeConvos#81]
**Describe the bug**
If you change the color of the texts you have sent there is no affect
**To Reproduce**
Change the color of either your texts or IMs there will be no change
**Expected behavior**
No change in the color of your sent messages
**Screenshots**
Can change receiver text color. Not my own
**Desktop (please complete the following information):**
- Device type: [iPhone 7] iPhone 7
 - iOS Version: [ex. 13.5.0] 13.5.0
 - Package Manager: [ex. Zebra, Installer, Cydia] Cydia
 - Tweak Version: [Can be found at the bottom of the settings page]
2.9.0
**Additional context**
I do really appreciate this tweak. If this is fixed it will be awesome. Also I paid for it and it suck that it doesn’t work

**Comment by nahtedetihw** [comment]
There must be something else override your message bubble colors. Can you tell me if you have enableUITheming in DopeConvos enabled? Also, does the issue persist if DopeConvos is the only tweak enabled?

**Comment by td-boop** [comment]
I managed to fix it using the gradient option. Confused me but it’s now
totally stable. Thank you for your contribution to the jailbreaking
community. This project is awesome
