### ISSUE TITLE
Can’t use Gamepigeon

### ISSUE THREAD

**Issue by TheSlimerX** [MTACS/DopeConvos#82]
**The bug**
I can’t tap on a game pigeon box when someone sends it to me with dope convos on.

**How To Reproduce**
- Have someone send you 8-ball* (or whatever)
- try and tap on it
- turn off dope convos
- try tapping it again (it should work)

*you can also send one to yourself
**update: you can but it works!! it doesn't work when you are texting someone else.

- Device type: iPhone 8
 - iOS Version: 13.4.1
 - Package Manager: Cydia
 - Tweak Version: 2.9

**Comment by TheSlimerX** [comment]
For some reason its working when I send one to myself.. but maybe still worth looking into?

**Comment by TheSlimerX** [comment]
**It only works when you are texting someone else!!!**

**Comment by nachobrobro** [comment]
I have the same problem too. Pretty annoying :(

**Comment by nahtedetihw** [comment]
DopeConvos>Bubbles>DisableMaskOnImages
