### ISSUE TITLE
Hide Contact Photos completely

### ISSUE THREAD

**Issue by samwllson9478** [MTACS/DopeConvos#88]
**Describe the feature you'd like to be added**
The contact Photos that either shows the contact photo or the person initials to be hidden. Also if that was possible would there be a way to automatically street hawkers out the persons name and message so there isn’t just an open blank space where the photo use to be. I think this would go great with iris

**Comment by nahtedetihw** [comment]
this can be done in stock apple settings>messages>disable contact photos
