### ISSUE TITLE
GamePigeon not working

### ISSUE THREAD

**Issue by elricfd** [MTACS/DopeConvos#9]
**Describe the bug**
GamePigeon messages wont open.

**To Reproduce**
Send a GamePigeon game to a friend.
**Expected behavior**
Tapping on the GamePigeon message usually opens up a gui, however, it doesn’t and instead won’t open.

**Screenshots**

**Desktop (please complete the following information):**
- Device type: iPhone X
 - iOS Version: 13.3
 - Package Manager: Zebra
 - Tweak Version: 1.1

**Additional context**

**Comment by nahtedetihw** [comment]
Please send a tweak list as we can play games fine. Must be something else conflicting

**Comment by nahtedetihw** [comment]
This is fixed as of version 1.6, use the option Disable Mask On Images located in DopeConvos>Bubbles
