### ISSUE TITLE
Literally doesn’t change ANYTHING...

### ISSUE THREAD

**Issue by jk3171** [MTACS/DopeConvos#93]
**Describe the bug**
The tweak is changing nothing and I can’t even pin conversations
**To Reproduce**
Literally only downloaded the tweak and changed a few colors and clicked Apply. Did nothing for me. Respringing does nothing. 
**Expected behavior**
Changes to the iMessage app. 
**Screenshots**
N/A
**Desktop (please complete the following information):**
- Device type: iPhone XR
 - iOS Version: iOS 13.5
 - Package Manager: Zebra
 - Tweak Version: 2.9

**Additional context**

**Comment by Hydroxing** [comment]
I had to do an ldrestart to fix. This happened to me once I had upgraded Link Identity Editor. Try an ldrestart and/or reinstall the tweak.

**Comment by nahtedetihw** [comment]
resolved in 4.0
