### ISSUE TITLE
Message colors not changing.

### ISSUE THREAD

**Issue by virusmod** [MTACS/DopeConvos#94]
**Describe the bug**
I hit apply when I change the settings for the tweak, but nothing changes. The ones I want are enabled, reset doesn’t change anything.

**To Reproduce**
Steps to reproduce the behavior: No idea, this is just happening.

**Expected behavior**
I expected the gradient to show up and app title to change but they didn’t.

**Screenshots**
I don’t think there can really be screenshots showing what’s happening.

**Desktop (please complete the following information):**
- Device type: [iPhone XR]
 - iOS Version: [ex. 13.5.1]
 - Package Manager: [Zebra/Cydia]
 - Tweak Version: (most recent)

**Additional context**

**Comment by csabo** [comment]
I’ve had this issue so much I’ve given up and am uninstalling the tweak and just pretending I lost $1.50 down the drain. 

I had intermittent luck doing a reset, then respring, then Toggle the enable toggle, then respring again, THEN if the preset didn’t randomly vanish (they do that) select it, apply, enable the tweak then respring a third time.

Just not a reliable tweak.

**Comment by nahtedetihw** [comment]
resolved in 4.0
