### ISSUE TITLE
Bug for Dope Convos

### ISSUE THREAD

**Issue by andmcc1** [MTACS/DopeConvos#95]
**Describe the bug*
For the option to use bubble outlines, the color of the outline stays the default color, blue, despite changing the color in settings. 

**To Reproduce**
Steps to reproduce the behavior: Disable gradient bubbles, enable outline bubbles and change the default blue iMessage color to another color. 

**Expected behavior**
I expected the iMessage sent outline bubble to be another color than blue. 

**Screenshots**

**Desktop (please complete the following information):**
- Device type: iPhone X
 - iOS Version: ex. 13.5
 - Package Manager: Cydia 
 - Tweak Version: 2.9

**Additional context**
Other than this I love the tweak, mkney well spent :)

**Comment by nahtedetihw** [comment]
outline bubbles has its own color separate from the gradient colors, please make sure you are using outline bubble colors
