### ISSUE TITLE
Closes 

### ISSUE THREAD

**Issue by mewuel** [MTACS/DopeConvos#96]
The messages app closes when I type and resprings then I can type but is the regular messages app 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by nahtedetihw** [comment]
fixed in 4.0
