### ISSUE TITLE
Light Mode compatibility.

### ISSUE THREAD

**Issue by LibanFlyer** [MTACS/DopeConvos#97]
**Describe the feature you'd like to be added**

Hello,

It would be nice to have DopeConvos be able to switch colors when the screen goes from dark to light mode so that light colors don’t appear very light. Also what fonts tend to blend with the white background instead of switching to black.

Thank you!

**Comment by thatcube** [comment]
+1 to this - id like to use my this tweak on automatic Dark/Light mode, so being able to set colors for both modes would be nice
