### ISSUE TITLE
Gamepigeon bug

### ISSUE THREAD

**Issue by imperialnemo** [MTACS/DopeConvos#98]
**Describe the bug**
Having issue with third-party imessage app called GamePigeon. Cannot access the game. 
**To Reproduce**
Download gamepigeon and select a game and try playing it. It wont allow you to press start/play

**Expected behavior**
When you send or someone send you a game, you can click play and itll take you to another screen to play the game. 
**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone 11 pro]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

**Comment by Hydroxing** [comment]
Did you Activate Disable Mask On Images?

**Comment by nahtedetihw** [comment]
Please enable Disable Mask On Images in DopeConvos>Main Settings>Bubbles>Disable Mask On Images
