### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Meme0911** [MTACS/DopeConvos#99]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Device type: [iPhone X]
 - iOS Version: [ex. 13.3.1]
 - Package Manager: [ex. Zebra, Installer, Cydia]
 - Tweak Version: [Can be found at the bottom of the settings page]

**Additional context**

It’s no longer theming or changing anything

**Comment by nahtedetihw** [comment]
resolved in 4.0
